# Generated by Django 5.0.4 on 2024-04-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_denuncia_descricao_denuncia_imagem_denuncia_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="denuncia",
            name="local_denuncia",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
